---
title: "COMPSCIX 415.2 Homework 1"
author: "Ehlan Siddiqi"
date: "6/11/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

My Github respository for my assignment cabe found at this URL :[https://github.com/ehlan/compscix-415-2-assignments](https://github.com/ehlan/compscix-415-2-assignments)

```{r load_packages, warning=FALSE, message=FALSE}
library(mdsr)
library(tidyverse)
```

```{r warning=FALSE, message=FALSE}
data("WorldCities")
```

Answer to Question1: I see 10 variables. I do not see any obersvation, but the Help document says there are 23,018 observations.

Answer to Question 2:

```{r warning=FALSE, message=FALSE}
region_col <- WorldCities$region
unique(region_col)
```

Answer to Question 3:
```{r, warning=FALSE, message=FALSE}
WorldCities %>% select(country) %>% unique()
```

Answer to Question 4:

```{r, warning=FALSE, message=FALSE}
WorldCities %>%  ggplot(aes(x= population)) + geom_histogram() + xlab('City Population') + ylab('Population Count') + ggtitle('My Title') + theme_bw(base_size = 11, base_family = "serif")
```

## finished assignment
